# Generated by Django 3.2.20 on 2023-07-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_to_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
