# Generated by Django 3.2.20 on 2023-07-29 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard_blog', '0003_auto_20230727_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parrent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='snowboard_blog.comment'),
        ),
    ]
