# Generated by Django 3.2.20 on 2023-07-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard_blog', '0004_comment_parrent_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parrent_comment',
            new_name='parrent_id',
        ),
    ]
