# Generated by Django 3.2.20 on 2023-07-29 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard_blog', '0006_rename_parrent_id_comment_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='snowboard_blog.comment'),
        ),
    ]
