# Generated by Django 3.2.20 on 2023-07-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard_blog', '0007_alter_comment_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_to_comments',
        ),
    ]
