# Generated by Django 3.2.20 on 2023-11-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowboard_blog', '0009_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='elevation',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the elevation of the slope in meters.', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slope_difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='EASY', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='snow_condition',
            field=models.CharField(choices=[('POWDER', 'Powder'), ('PACKED', 'Packed'), ('ICED', 'Iced'), ('SLUSHY', 'Slushy')], default='POWDER', max_length=250),
        ),
    ]
